### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by q2792479571** [pengboboer/alpha_player_plugin#1]
ARC Semantic Issue (Xcode): No visible @interface for 'BDAlphaPlayerMetalView' declares the selector 'stop'
/Users/connive/.pub-cache/hosted/pub.flutter-io.cn/alpha_player_plugin-0.0.1/ios/Classes/BDAlphaPlayer/BDAlphaPlayerMetalView.m:160:10

Uncategorized (Xcode): Command SwiftEmitModule failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

**Comment by pengboboer** [comment]
flutter sdk version ?

**Comment by Pgrammerybj** [comment]
ios运行报错，BDAlphaPlayerMetalView.m中的stop方法被注释掉了，麻烦大佬修复一下 @pengboboer

**Comment by ke112** [comment]
最新版已解决
